events {
    worker_connections 1024;
}

http {
    server {
        listen 80;
        location / {
            proxy_pass http://balance-web-app-1:3000;
        }
        location /api/ {
            proxy_pass http://balance-api-gateway-1:8000/;
        }
    }
}
